### ISSUE TITLE
partition vs sharded: breakage

### ISSUE THREAD

**Issue by jamiefry-datatonic** [looker/block-bigquery-optimization#21]
1. 

The new log install process lands the data in a partitioned format detailed in the readme. The old sink process landed data as a table sharded (which was the only available few years ago), which required the following: 
{% condition date_filter %} PARSE_TIMESTAMP('%E4Y%m%d', _TABLE_SUFFIX) {% endcondition %} ;;
in the bigquery_data_access_core view. This will now break if anyone has pulled the logs as a partitioned table. 
please see this commit change in our public repo for this block, which switches to handling partition tables over sharded:
_https://github.com/teamdatatonic/looker-gcp-control/commit/f6c2a2ecda1e1c65834747599df64fae29_

Note, when creating the sink, the user still has the option to use sharded tables, but this is ill advised. 

2.

The following should be added to the readme, because it details how the logs have been unioned, important to understand if any new modelling is added to the lookml layer: 

> The BigQuery Audit Logs export pulls in both the AuditData and BigQueryAuditMetadata logs. AuditData is the older version of the logs, and BigQueryAuditMetadata is the new which ADDS new columns. These are therefore unioned in the table. The lookml model pulls from the older version, but you have the ability to model the new columns into the model should you wish. You should only use ROW COUNT with Method Name filter applied.

**Comment by jeffrey-martinez** [comment]
Thank you @jamiefry-datatonic and I'm so sorry it took forever to get to this. https://github.com/looker/block-bigquery-optimization/pull/22 covers the changes you mentioned. Thank you!
